import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TemplateProvider from "@/context/TemplateContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TemplateProvider>
        <body className="antialiased bg-gray-50">
          <Header />

          <main className="min-h-screen">
            <div className="max-w-[95%] mx-auto py-4">{children}</div>
          </main>

          <Footer />
        </body>
      </TemplateProvider>
    </html>
  );
}
